version: '2'

services:
  survey:
    build: 
      context: .
        
    ports:
      - '${SURVEY_APP_PORT}:80'
          
    environment: 
      - MODULE_NAME=main
      - MONGO_USERNAME=${MONGODB_USERNAME}
      - MONGO_PASSWORD=${MONGODB_PASSWORD}
      - MONGO_HOST=${MONGODB_HOST}
      - MONGO_PORT=${MONGODB_PORT}

    command: /start-reload.sh

    volumes: 
      - ./app:/app
    
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    volumes:
      - mongodb_data_container:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "${MONGO_EXPRESS_PORT}:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_PASSWORD}
    
      


  
volumes:
  mongodb_data_container:
